### ISSUE TITLE
Add Movie Button

### ISSUE THREAD

**Issue by ccasalme** [ccasalme/Movie-MatchMaker#12]
# Need a responsive button
- [x] HTML: Structure for Button and Modal - Parsons
- [x] CSS: Styling the Modal - Casalme
- [x] JavaScript: Displaying and Hiding the Modal - Bontrager

**Comment by cpars** [comment]
Reviewing HTML/CSS code that was added

**Comment by ccasalme** [comment]
Modal window added Bontrager and debugged Casalme
Styled Parsons

**Comment by ccasalme** [comment]
completed!
