### ISSUE TITLE
HTML Requests from Design

### ISSUE THREAD

**Issue by ArtOfTheNiles** [ccasalme/Movie-MatchMaker#17]
#BLOCKERS
- [ ] All HTML elements are nested in the Header, so it cannot be styled separately.
- [ ] Movie List Items get a dedicated container, currently each list is an item itself.

#REQUESTS
- [ ] Movie Matchmaker (`h1`) and Search Bar (`nav`) share a container
- [ ] Filter tags get a dedicated container
- [ ] A section between `.actors` and `.more-details-button` for more-details' items
    - (In order to keep the details between it and the 'actors' line)
- [ ] A copy of the `more-details-button`... for a `less-details-button`!
- [ ] A section labeled `user-details` that will contain the user details we want to add
    - This will fill the space where the movie score currently sits
    - [ ] **Watched-It** button
        - JS - clicking it should prompt the user if they want to delete their notes 
            and score to start over or cancel
    - [ ] user-score: 1-5 stars
        - Pre **Watched-It** text: Anticipation Score(?)
        - Post **Watched-It** text: Opinion Score(?)
        - (_Text might not even be necessary_)
    - [ ] user-notes: text field for user notes, 3 lines min with line wrap
        - field title: Thoughts:
        - pre-filled pre-watch text: "I want to see this movie because..." 
        - pre-filled post-watch text: "So this is what I thought about it..."
- [ ] Replace Filter Button with "Filters:" text in `nav-tabs`
- [ ] Change movie rating from text to ⭐⭐⭐⭐⭐
- [ ] Add Movie button could be a sticky footer

**Comment by NguyenTranThanhTu** [comment]
hello can i help you with this issue
